primary:

  AK:
    overseerScript: page.manualWait(); await page.waitForDelay(30000); page.done();
    message: waiting 30 seconds for AK

  AL:
    renderSettings:
      viewport:
        width: 3000
        height: 1400
    overseerScript: >
      page.manualWait();
      await page.waitForSelector("#ember349.ember-view");
      page.click("#ember349.ember-view");
      await page.waitForDelay(2000);
      page.done();
    message: clicking on tab 11 for AL

  AR:
    renderSettings:
      viewport:
        width: 3000
        height: 1400
    overseerScript: >
      page.manualWait();
      await page.waitForSelector("#ember364.ember-view");
      page.click("#ember364.ember-view");
      await page.waitForDelay(2000);
      page.done();
    message: clicking on "COVID-19 Deaths" for AR

  AZ:
    overseerScript: >
      page.manualWait();
      await page.waitForSelector(".congregate-settings");
      page.click(".congregate-settings");
      await page.waitForDelay(5000);
      page.done();
    message: clicking on "congregate settings" for AZ, wait 5 sec

  CA:
    renderSettings:
      viewport:
        width: 1400
        height: 8500
    message: using viewport height 8500 for CA

  FL:
    file: pdf
    message: downloading pdf for FL

  KS:
    file: pdf
    message: downloading pdf for KS

  KY:
    file: pdf
    message: downloading pdf for KY

  MS:
    file: pdf
    message: downloading pdf for MS

  NJ:
    file: xlsx
    message: downloading xlsx for MS

  NY:
    file: pdf
    message: downloading pdf for NY

  OK:
    renderSettings:
      viewport:
        width: 1400
        height: 3000
    overseerScript: >
      page.manualWait();
      await page.waitForSelector("button.prefix-overlay-close");
      page.click("button.prefix-overlay-close");
      await page.waitForFunction(()=>document.querySelector("#main-content").textContent!=="");
      await page.waitForDelay(10000);
      page.done();
    message: clicking button to get rid of popup for OK, then waiting 10 sec. Also larger viewport

  PA:
    renderSettings:
      viewport:
        width: 1400
        height: 7000
    message: using viewport height 7000 for PA

  TX:
    file: xls
    message: downloading Excel for FL

  UT:
    overseerScript: page.manualWait(); await page.waitForDelay(40000); page.done();
    renderSettings:
      clipRectangle:
        width: 1400
        height: 1500
    message: UT dashboard doesn't render in phantomjscloud unless we set clipRectangle; wait 40 sec

  WA:
    file: pdf
    message: downloading pdf for WA

  WV:
    overseerScript: page.manualWait(); await page.waitForDelay(30000); page.done();
    renderSettings:
      viewport:
        width: 1400
        height: 4000
    message: waiting 30 seconds for WV, and using larger viewport

secondary:

  CA:
    file: pdf
    message: downloading pdf for CA secondary

  FL:
    file: pdf
    message: downloading pdf for FL secondary

  MN:
    overseerScript: >
      page.manualWait();
      await page.waitForSelector("#accordion div:nth-child(49) .panel-heading p");
      page.click("#accordion div:nth-child(49) .panel-heading p");
      await page.waitForDelay(1000);
      page.done();
    message: clicking on a dropdown for MN secondary

  MS:
    file: pdf
    message: downloading pdf for MS secondary

  NC:
    file: pdf
    message: downloading pdf for NC secondary

  NJ:
    overseerScript: >
      page.manualWait();
      await page.waitForSelector("[aria-label='Go to entry 4: Long Term Care']");
      page.click("[aria-label='Go to entry 4: Long Term Care']", delay=1000);
      await page.waitForDelay(30000);
      page.done();
    message: custom clicking for NJ secondary, wait 20 sec

  PA:
    file: xlsx
    message: downloading xlsx for PA secondary

  OR:
    file: pdf
    message: downloading pdf for OR secondary

  TX:
    file: xls
    message: downloading Excel for TX secondary

tertiary:

  MS:
    file: pdf
    message: downloading pdf for MS tertiary

  PA:
    file: xlsx
    message: downloading xlsx for PA tertiary
