primary:

  AL:
    renderSettings:
      viewport:
        width: 3000
        height: 1400
    overseerScript: >
      page.manualWait();
      await page.waitForSelector("#ember353.ember-view");
      page.click("#ember353.ember-view");
      await page.waitForDelay(2000);
      page.done();
    message: clicking on tab 12 for AL

  AZ:
    overseerScript: >
      page.manualWait();
      await page.waitForSelector(".demodashboard");
      page.click(".demodashboard");
      await page.waitForFunction(()=>document.querySelector("#subcontent").textContent!=="");
      await page.waitForDelay(10000);
      page.done();
    message: custom mouseover logic for AZ, wait 10 sec

  CA:
    renderSettings:
      viewport:
        width: 1400
        height: 6500
    message: using viewport height 6500 for CA

  CT:
    file: pdf
    message: downloading pdf for CT

  DC:
    file: xlsx
    message: downloading xlsx for DC

  FL:
    file: pdf
    message: downloading pdf for FL

  GA:
    file: zip
    message: downloading zip for GA

  GU:
    renderSettings:
      viewport:
        width: 3000
        height: 1400
    overseerScript: >
      page.manualWait();
      await page.waitForSelector("#ember125.ember-view");
      page.click("#ember125.ember-view");
      await page.waitForDelay(1000);
      page.done();
    message: clicking on "Cases by Ethnicity" tab for GU

  IA:
    overseerScript: page.manualWait(); await page.waitForDelay(30000); page.done();
    message: waiting 30 seconds for IA

  ID:
    overseerScript: >
      page.manualWait();
      await page.waitForSelector(".tabStoryPoint.tab-widget");
      page.click(".tabStoryPoint.tab-widget:nth-of-type(2)");
      await page.waitForDelay(2000);
      page.done();
    message: clicking on "Statewide Demographics" for ID, wait 2 sec

  IN:
    file: xlsx
    message: downloading xlsx for IN

  KY:
    file: pdf
    message: downloading pdf for KY

  MA:
    file: pdf
    message: downloading pdf for MA

  NE:
    renderSettings:
      viewport:
        width: 3000
        height: 1400
    overseerScript: >
      page.manualWait();
      await page.waitForSelector("#ember427.ember-view");
      page.click("#ember427.ember-view");
      await page.waitForDelay(3000);
      page.done();
    message: stuff

  NJ:
    file: pdf
    message: downloading pdf for NJ

  TX:
    file: xlsx
    message: downloading xlsx for TX

secondary:

  AL:
    renderSettings:
      viewport:
        width: 3000
        height: 1400
    overseerScript: >
      page.manualWait();
      await page.waitForSelector("#ember357.ember-view");
      page.click("#ember357.ember-view");
      await page.waitForDelay(2000);
      page.done();
    message: clicking on tab 13 for AL secondary

  AR:
    overseerScript: >
      page.manualWait();
      await page.waitForSelector("#ember366");
      page.click("#ember366");
      await page.waitForDelay(5000);
      page.done();
    message: custom tab click logic for AR secondary, wait 5 sec

  AZ:
    overseerScript: >
      page.manualWait();
      await page.waitForSelector(".hospitalizationdashboard");
      page.click(".hospitalizationdashboard");
      await page.waitForFunction(()=>document.querySelector("#subcontent").textContent!=="");
      await page.waitForDelay(10000);
      page.done();
    message: custom click logic for AZ secondary, wait 10 sec

  IA:
    overseerScript: page.manualWait(); await page.waitForDelay(30000); page.done();
    message: waiting 30 seconds for IA secondary

  ID:
    overseerScript: >
      page.manualWait();
      await page.waitForSelector(".tabStoryPoint.tab-widget");
      page.click(".tabStoryPoint.tab-widget:nth-of-type(7)");
      await page.waitForDelay(2000);
      page.done();
    message: clicking on "Deaths Demographics" for ID secondary, wait 2 sec

  MI:
    file: xlsx
    message: downloading xlsx for MI secondary

  MO:
    overseerScript: >
      page.manualWait();
      await page.waitForSelector("[aria-label='Go to entry 2: Cases - Demographics']");
      page.click("[aria-label='Go to entry 2: Cases - Demographics']", delay=500);
      await page.waitForDelay(20000);
      page.done();
    message: custom clicking for MO secondary, wait 10 sec


  TN:
    file: xlsx
    message: downloading xlsx for TN secondary

tertiary:

  AR:
    overseerScript: >
      page.manualWait();
      await page.waitForSelector("#ember376");
      page.click("#ember376");
      await page.waitForDelay(5000);
      page.done();
    message: custom tab click logic for AR tertiary, wait 5 sec

  AZ:
    overseerScript: >
      page.manualWait();
      await page.waitForSelector(".deathdashboard");
      page.click(".deathdashboard");
      await page.waitForFunction(()=>document.querySelector("#subcontent h2").textContent=="COVID-19 Deaths");
      await page.waitForDelay(10000);
      page.done();
    message: custom mouseover logic for AZ tertiary, wait 10 sec

  MO:
    overseerScript: >
      page.manualWait();
      await page.waitForSelector("[aria-label='Go to entry 6: Deaths']");
      page.click("[aria-label='Go to entry 6: Deaths']");
      await page.waitForDelay(10000);
      page.done();
    message: custom clicking for MO tertiary, wait 10 sec
