# This workflow archives published CDC county-level data if there are changes every day

name: Update CDC state files

on:
  schedule:
    # Run every day at midnight.
    - cron:  '0 0 * * *'

jobs:
  update:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Scrape CDC county level data for each state
      run: |
        python3 -m pip install -r data-collection-scripts/cdc-by-state/requirements.txt
        python3 data-collection-scripts/cdc-by-state/scrape.py

    - name: Commit
      uses: stefanzweifel/git-auto-commit-action@v4.1.2
      with:
        commit_message: Updating CDC county level data for each state
        file_pattern: data/*
        commit_author: GitHub Actions <actions@github.com>
