# This workflow archives published data if there are changes every hour

name: Update HHS and CDC files

on:
  schedule:
    # Run every hour, on the half-hour.
    - cron:  '30 * * * *'

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - run:  curl https://healthdata.gov/api/views/6xf2-c3ie/rows.csv?accessType=DOWNLOAD -o data/hhs/reported_hospital_utilization_$(TZ=America/New_York date '+%Y%m%d').csv
    - run:  curl https://healthdata.gov/api/views/g62h-syeh/rows.csv?accessType=DOWNLOAD -o data/hhs/reported_hospital_utilization_timeseries_$(TZ=America/New_York date '+%Y%m%d').csv
    - run:  curl https://healthdata.gov/api/views/j8mb-icvb/rows.csv?accessType=DOWNLOAD -o data/hhs/covid-19_diagnostic_lab_testing_$(TZ=America/New_York date '+%Y%m%d').csv
    - run:  curl https://healthdata.gov/api/views/anag-cw7u/rows.csv?accessType=DOWNLOAD -o data/hhs/reported_hospital_capacity_admissions_facility_level_weekly_average_timeseries_$(TZ=America/New_York date '+%Y%m%d').csv && gzip data/hhs/reported_hospital_capacity_admissions_facility_level_weekly_average_timeseries_$(TZ=America/New_York date '+%Y%m%d').csv

    - run:  curl https://healthdata.gov/api/views/7ctx-gtb7/rows.csv?accessType=DOWNLOAD -o data/hhs/estimated_icu_$(TZ=America/New_York date '+%Y%m%d').csv
    - run:  curl https://healthdata.gov/api/views/jjp9-htie/rows.csv?accessType=DOWNLOAD -o data/hhs/estimated_inpatient_all_$(TZ=America/New_York date '+%Y%m%d').csv
    - run:  curl https://healthdata.gov/api/views/py8k-j5rq/rows.csv?accessType=DOWNLOAD -o data/hhs/estimated_inpatient_covid_$(TZ=America/New_York date '+%Y%m%d').csv

    - run:  curl https://covid.cdc.gov/covid-data-tracker/COVIDData/getAjaxData?id=vaccination_data -o data/cdc_vaccinations.json
    - run:  curl https://covid.cdc.gov/covid-data-tracker/COVIDData/getAjaxData?id=US_MAP_TESTING -o data/cdc_testing.json
    - run:  curl https://data.cdc.gov/api/views/9mfq-cb36/rows.csv?accessType=DOWNLOAD -o data/cdc_cases_deaths.csv
    - run:  curl https://covid.cdc.gov/covid-data-tracker/COVIDData/getAjaxData?id=integrated_county_latest_external_data -o data/cdc_counties.csv
    - run:  curl https://www.cdc.gov/coronavirus/2019-ncov/modules/lineage-cases.json -o data/cdc_b117_cases.json
    - run:  curl https://covid.cdc.gov/covid-data-tracker/COVIDData/getAjaxData?id=vaccination_ltc_data -o data/cdc_vaccinations_ltc.json
    - run:  curl https://covid.cdc.gov/covid-data-tracker/COVIDData/getAjaxData?id=vaccination_trends_data -o data/cdc_vaccination_trends.json
    - run:  curl https://covid.cdc.gov/covid-data-tracker/COVIDData/getAjaxData?id=vaccination_demographics_data -o data/cdc_vaccinations_demographics.json
    - run:  curl https://healthdata.gov/api/views/di4u-7yu6/rows.csv?accessType=DOWNLOAD -o data/hhs/community_profile_counties_$(TZ=America/New_York date '+%Y%m%d').csv
    - run:  curl "https://data.cdc.gov/api/views/r8kw-7aab/rows.csv?accessType=DOWNLOAD" -o data/cdc_provisional_deaths.csv
    - name: Commit
      uses: stefanzweifel/git-auto-commit-action@v4.1.2
      with:
        commit_message: Updating HHS data backups
        file_pattern: data/*
        commit_author: GitHub Actions <actions@github.com>
