name: Update CDC timeseries

on:
  schedule:
    - cron: '55 * * * *'

defaults:
  run:
     working-directory: data-collection-scripts/cdc-vaccinations-timeseries/

jobs:
  update:
      runs-on: ubuntu-20.04
      steps:
        - uses: actions/checkout@v2
          with:
            fetch-depth: 0
        - uses: actions/cache@v2
          with:
            path: ~/.cache/pip
            key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
            restore-keys: |
              ${{ runner.os }}-pip-
        - name: Use Python
          uses: actions/setup-python@v2
          with:
            python-version: '3.9'
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        - name: Run script
          run: |
            python make_timeseries.py > ../../data/cdc_vaccinations_timeseries.csv
            python make_timeseries.py --strip-duplicate-days > ../../data/cdc_vaccinations_timeseries_daily.csv
        - name: Commit
          if: github.ref == 'refs/heads/master'
          uses: EndBug/add-and-commit@v5
          with:
            message: Updating timeseries
            add: 'data/cdc_vaccinations_timeseries*'
            author_name: GitHub Actions
            author_email: actions@github.com
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
