# This workflow archives published data if there are changes every hour

name: Update HHS and CDC files

on: 
  schedule:
    # Run every hour, on the half-hour.
    - cron:  '30 * * * *'

jobs:
  update:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    
    - name: Download HHS and CDC files
      run: |
        HHS_HOSP_LINK=`curl -k https://healthdata.gov/dataset/covid-19-reported-patient-impact-and-hospital-capacity-state | grep -Eo "https?://\S+?\.csv"`
        HHS_NEW_HOSP_LINK=`curl -k https://healthdata.gov/dataset/covid-19-reported-patient-impact-and-hospital-capacity-state-timeseries | grep -Eo "https?://\S+?\.csv"`
        HHS_TEST_LINK=`curl -k https://healthdata.gov/dataset/covid-19-diagnostic-laboratory-testing-pcr-testing-time-series | grep -Eo "https?://\S+?\.csv"`
        HHS_FACILITY_LINK=`curl -k https://healthdata.gov/dataset/covid-19-reported-patient-impact-and-hospital-capacity-facility | grep -Eo "https?://\S+?\.csv"`
        cd data/hhs && { curl -k $HHS_HOSP_LINK -O; curl -k $HHS_TEST_LINK -O; curl -k $HHS_NEW_HOSP_LINK -O; curl -k $HHS_FACILITY_LINK -O; cd -; }
        curl -k https://healthdata.gov/dataset/covid-19-estimated-patient-impact-and-hospital-capacity-state | grep -Eo "https?://\S+?\.csv" | while read -r line ; do
          cd data/hhs && { curl -k $line -O; cd -; }
        done
        curl https://covid.cdc.gov/covid-data-tracker/COVIDData/getAjaxData?id=vaccination_data -o data/cdc_vaccinations.json
        curl https://data.cdc.gov/api/views/9mfq-cb36/rows.csv?accessType=DOWNLOAD -o data/cdc_cases_deaths.csv
        curl https://covid.cdc.gov/covid-data-tracker/COVIDData/getAjaxData?id=integrated_county_latest_external_data -o data/cdc_counties.csv
        curl https://www.cdc.gov/coronavirus/2019-ncov/modules/lineage-cases.json -o data/cdc_variants.json
        curl https://covid.cdc.gov/covid-data-tracker/COVIDData/getAjaxData?id=vaccination_ltc_data -o data/cdc_vaccinations_ltc.json

    - name: Commit
      uses: stefanzweifel/git-auto-commit-action@v4.1.2
      with:
        commit_message: Updating HHS data backups
        file_pattern: data/*
        commit_author: GitHub Actions <actions@github.com>
